services:
  apache:
    image: httpd:latest
    restart: always
    container_name: my-apache-app
    ports:
      - "8080:8080"
    volumes:
      - ./website:/usr/local/apache2/htdocs
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    image: felixwegener/nodejs-image-backend
    restart: always
    ports:
      - "4000:4000"
    expose:
      - "4000:4000"
volumes:
  my-db:
